Change CircleCI config to support live (#1711)
Default cluster is live-1 but will be changed to live when all environments are migrated

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -324,6 +324,33 @@ commands:
           name: check image
           command: docker images
 
+  export_kube_vars:
+    description: "Exports kube vars for the chosen environment and cluster."
+    parameters:
+      env:
+        type: string
+      cluster:
+        type: string
+        default: "live-1"
+    steps:
+      - run:
+          name: Export kubernetes env vars
+          command: |
+            ENV_UPCASED=$(echo "<< parameters.env >>" | tr '[:lower:]' '[:upper:]')
+            [[ "<< parameters.cluster >>" = "live" ]] && CLUSTER_SUFFIX="_LIVE"
+
+            CLUSTER_VAR="KUBE_CLUSTER${CLUSTER_SUFFIX}"
+            CACERT_VAR="KUBE_ENV_${ENV_UPCASED}_CACERT${CLUSTER_SUFFIX}"
+            NAME_VAR="KUBE_ENV_${ENV_UPCASED}_NAME"
+            NAMESPACE_VAR="KUBE_ENV_${ENV_UPCASED}_NAMESPACE"
+            TOKEN_VAR="KUBE_ENV_${ENV_UPCASED}_TOKEN${CLUSTER_SUFFIX}"
+
+            echo "export KUBE_CLUSTER=\"${!CLUSTER_VAR}\"" >> $BASH_ENV
+            echo "export KUBE_CACERT=\"${!CACERT_VAR}\"" >> $BASH_ENV
+            echo "export KUBE_NAME=\"${!NAME_VAR}\"" >> $BASH_ENV
+            echo "export KUBE_NAMESPACE=\"${!NAMESPACE_VAR}\"" >> $BASH_ENV
+            echo "export KUBE_TOKEN=\"${!TOKEN_VAR}\"" >> $BASH_ENV
+
   retag_docker_image:
     description: "Re-tag an image for deployment."
     parameters:
@@ -340,40 +367,58 @@ commands:
           command: |
             MANIFEST=$(aws ecr batch-get-image --repository-name "${GITHUB_TEAM_NAME_SLUG}/${CIRCLE_PROJECT_REPONAME}" \
             --image-ids imageTag=${CIRCLE_SHA1} --query 'images[].imageManifest' --output text)
-            aws ecr put-image --repository-name "${GITHUB_TEAM_NAME_SLUG}/${CIRCLE_PROJECT_REPONAME}" --image-tag << parameters.env >>.latest \
-            --image-manifest "${MANIFEST}"
+            set +e
+            PUT_RESULT=$(aws ecr put-image --repository-name "${GITHUB_TEAM_NAME_SLUG}/${CIRCLE_PROJECT_REPONAME}" --image-tag << parameters.env >>.latest \
+            --image-manifest "${MANIFEST}")
+            set -e
+
+            # ImageAlreadyExistsException can be thrown if we re-run a failed deployment, so ignore it
+            if [[ $? != "0" && $PUT_RESULT != *"ImageAlreadyExistsException"* ]]; then
+              exit 1
+            fi
 
   deploy_to_k8s:
     description: "Deploys a previously built Docker image to dev/staging/preprod/production k8s environment"
     parameters:
       env:
         type: string
+      cluster:
+        type: string
+        default: "live-1"
       notify_slack:
         type: string
         default: ""
+      run_migrations:
+        type: boolean
+        default: true
     steps:
       - checkout
-
-      # This step leverages cloud platform. There needs to be 4 env variables in Circle CI named KUBE_ENV_<env>_* to
-      # support this. Details at:
-      # https://user-guide.cloud-platform.service.justice.gov.uk/documentation/deploying-an-app/use-circleci-to-upgrade-app.html#creating-a-service-account-for-circleci
+      - export_kube_vars:
+          env: << parameters.env >>
+          cluster: << parameters.cluster >>
       - run:
-          name: kubectl use context
+          name: Authenticate with cluster
           command: |
-            setup-kube-auth
-            kubectl config use-context << parameters.env >>
-      - run:
-          name: run db migrations
-          command: |
-            set -o errexit
-            sed 's/__ENV__/<< parameters.env >>/' k8s_migrate_job.yml | kubectl apply -f -
-            kubectl wait --for=condition=complete --timeout=300s job/hmpps-book-secure-move-api-migrate-db-<< parameters.env >>
-            exit_code=$?
-            kubectl logs job/hmpps-book-secure-move-api-migrate-db-<< parameters.env >>
-            kubectl delete job/hmpps-book-secure-move-api-migrate-db-<< parameters.env >>
-            exit ${exit_code}
+            echo -n $KUBE_CACERT | base64 -d > ./ca.crt
+            kubectl config set-cluster ${KUBE_CLUSTER} --certificate-authority=./ca.crt --server=https://${KUBE_CLUSTER}
+            kubectl config set-credentials circleci --token=${KUBE_TOKEN}
+            kubectl config set-context ${KUBE_CLUSTER} --cluster=${KUBE_CLUSTER} --user=circleci --namespace=${KUBE_NAMESPACE}
+            kubectl config use-context ${KUBE_CLUSTER}
+      - when:
+          condition: <<parameters.run_migrations>>
+          steps:
+            - run:
+                name: run db migrations
+                command: |
+                  set -o errexit
+                  sed 's/__ENV__/<< parameters.env >>/' k8s_migrate_job.yml | kubectl apply -f -
+                  kubectl wait --for=condition=complete --timeout=300s job/hmpps-book-secure-move-api-migrate-db-<< parameters.env >>
+                  exit_code=$?
+                  kubectl logs job/hmpps-book-secure-move-api-migrate-db-<< parameters.env >>
+                  kubectl delete job/hmpps-book-secure-move-api-migrate-db-<< parameters.env >>
+                  exit ${exit_code}
       - deploy:
-          name: rolling update image to << parameters.env >>
+          name: rolling update image to << parameters.env >> on << parameters.cluster >>
           command: |
             export BUILD_DATE=$(date -Is) >> $BASH_ENV
             source $BASH_ENV
@@ -487,6 +532,7 @@ jobs:
           env: "dev"
       - deploy_to_k8s:
           env: "dev"
+          cluster: "live"
 
   deploy_uat:
     resource_class: small
@@ -498,6 +544,16 @@ jobs:
       - deploy_to_k8s:
           env: "uat"
 
+  deploy_uat_live:
+    resource_class: small
+    executor: cloud-platform-executor
+    steps:
+      - setup_remote_docker
+      - deploy_to_k8s:
+          env: "uat"
+          cluster: "live"
+          run_migrations: false
+
   deploy_staging:
     resource_class: small
     executor: cloud-platform-executor
@@ -507,6 +563,16 @@ jobs:
           env: "staging"
       - deploy_to_k8s:
           env: "staging"
+
+  deploy_staging_live:
+    resource_class: small
+    executor: cloud-platform-executor
+    steps:
+      - setup_remote_docker
+      - deploy_to_k8s:
+          env: "staging"
+          cluster: "live"
+          run_migrations: false
 
   deploy_preprod:
     resource_class: small
@@ -518,6 +584,16 @@ jobs:
       - deploy_to_k8s:
           env: "preprod"
 
+  deploy_preprod_live:
+    resource_class: small
+    executor: cloud-platform-executor
+    steps:
+      - setup_remote_docker
+      - deploy_to_k8s:
+          env: "preprod"
+          cluster: "live"
+          run_migrations: false
+
   deploy_production:
     resource_class: small
     executor: cloud-platform-executor
@@ -528,6 +604,17 @@ jobs:
       - deploy_to_k8s:
           env: "production"
           notify_slack: "true"
+
+  deploy_production_live:
+    resource_class: small
+    executor: cloud-platform-executor
+    steps:
+      - setup_remote_docker
+      - deploy_to_k8s:
+          env: "production"
+          notify_slack: "true"
+          cluster: "live"
+          run_migrations: false
 
   ecr-cleanup:
     resource_class: small
@@ -613,13 +700,31 @@ workflows:
           <<: *only_main
           requires:
             - build_image
+      - deploy_staging_live:
+          context:
+            - hmpps-common-vars
+          <<: *only_main
+          requires:
+            - build_image
       - deploy_uat:
           context:
             - hmpps-common-vars
           <<: *only_deploy_tags
           requires:
             - build_image
+      - deploy_uat_live:
+          context:
+            - hmpps-common-vars
+          <<: *only_deploy_tags
+          requires:
+            - build_image
       - deploy_preprod:
+          context:
+            - hmpps-common-vars
+          <<: *only_deploy_tags
+          requires:
+            - build_image
+      - deploy_preprod_live:
           context:
             - hmpps-common-vars
           <<: *only_deploy_tags
@@ -637,6 +742,12 @@ workflows:
           requires:
             - build_image
       - deploy_production:
+          context:
+            - hmpps-common-vars
+          <<: *only_deploy_tags
+          requires:
+            - hold_production
+      - deploy_production_live:
           context:
             - hmpps-common-vars
           <<: *only_deploy_tags
